-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 13:10:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `id` TINYINT(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` SMALLINT(3) UNSIGNED NOT NULL,
  `name` VARCHAR(85) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `posts_id` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`, `posts_id`),
  INDEX `fk_user_roles_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles`
    FOREIGN KEY (`posts_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`convoy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`convoy` (
  `idconvoy` INT NOT NULL AUTO_INCREMENT,
  `pretime` DATETIME NOT NULL,
  `time` DATETIME NOT NULL,
  `save_link` VARCHAR(130) NULL,
  `px_channel` TINYINT(2) NULL,
  `server_number` TINYINT(1) NULL,
  `instructions` TEXT(500) NULL,
  `user_id` SMALLINT(3) UNSIGNED NOT NULL,
  `user_posts_id` TINYINT(2) NOT NULL,
  PRIMARY KEY (`idconvoy`, `user_id`, `user_posts_id`),
  INDEX `fk_convoy_user1_idx` (`user_id` ASC, `user_posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_convoy_user1`
    FOREIGN KEY (`user_id` , `user_posts_id`)
    REFERENCES `mydb`.`user` (`id` , `posts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
